import = [
    "~/.config/alacritty/tokyo-night.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.9
decorations = "Buttonless"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font", style = "BoldItalic" }
size = 15
